SELECT h.CODE, h.NOMPROP, h.CODEEPI, e.CODE, e.DESCRIPTION
FROM HEBERGEMENT 
INNER JOIN EPI ON h.CODEEPI = e.CODE
ORDER BY e.CODE;

SELECT CODE, TARIFSBASECHAMBRE AS TARIF, TARIFBASELITSUP,CAPACITE
FROM HEBERGEMENT
ORDER BY TARIF ASC;
